version: '3.8'

services:
  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: task_manager_db
    ports:
      - "5432:5432"
    networks:
      - app-network

  app:
    build: .
    ports:
      - "3000:3000"
    environment:
      DB_HOST: db
      DB_USER: postgres
      DB_PASSWORD: root
      DB_NAME: task_manager_db
    depends_on:
      - db
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
